# Generated by Django 5.1.7 on 2025-04-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='id',
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
